# Generated by Django 4.2.6 on 2023-12-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_tabla_test_numeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('tipo_gasolina', models.CharField(max_length=30, null=True)),
                ('motor', models.CharField(max_length=30, null=True)),
                ('transmision', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20, null=True)),
                ('cambio_volante', models.BooleanField(null=True)),
                ('tipo_auto', models.CharField(max_length=20, null=True)),
                ('numero_asientos', models.IntegerField(null=True)),
                ('descripcion', models.TextField(max_length=400, null=True)),
                ('auto_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('administrador', models.BooleanField(default=False)),
                ('usuario_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('registro_delete', models.DateTimeField(null=True)),
                ('auto_registro_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina.autos')),
                ('usuario_registro_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pagina.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('auto_notificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.autos')),
                ('usuario_notificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_foto', models.FilePathField()),
                ('auto_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina.autos')),
            ],
        ),
        migrations.CreateModel(
            name='Contraseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contra', models.CharField(max_length=600)),
                ('contra_delete', models.DateTimeField(null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
    ]
