# Generated by Django 4.2.6 on 2023-12-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_autos_usuarios_registros_visitas_notificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='color',
            field=models.CharField(choices=[('1', 'Rojo'), ('2', 'Azul'), ('3', 'Verde'), ('4', 'Rosa'), ('5', 'Blanco'), ('6', 'Negro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='autos',
            name='motor',
            field=models.CharField(choices=[('1', 'Tipo V'), ('2', 'Tipo W'), ('3', 'Cilindro opuesto'), ('4', 'Electrico')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='autos',
            name='tipo_auto',
            field=models.CharField(choices=[('1', 'Sedan'), ('2', 'SUV'), ('3', 'Deportivo'), ('4', 'Hibrido'), ('5', 'Electrico'), ('6', 'Camion')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='autos',
            name='tipo_gasolina',
            field=models.CharField(choices=[('1', '93'), ('2', '95'), ('3', '97'), ('4', 'Petrolero')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='autos',
            name='transmision',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')]),
        ),
    ]
