# Generated by Django 5.0 on 2023-12-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_autos_color_alter_autos_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
