# Generated by Django 4.2.6 on 2023-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_autos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
