# Generated by Django 5.0 on 2023-12-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contraseñas',
            new_name='Contrasenas',
        ),
    ]
