# Generated by Django 5.0 on 2023-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_alter_fotos_path_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='path_foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
